dracut/80setup-root/pre-pivot-setup-root.sh

This feels a bit weird doing the remount in this module, but I don't really have any better ideas.

dracut: don't explicitly remount /sysroot rw

---

dracut/10verity-generator/verity-generator

By default services depend on `basic.target` but this is problematic for
anything directly in the dependency tree for `initrd-switch-root.target`
as it means everything under `basic.target` will not be stopped prior to
the switch root. This leads to all sorts of surprising things, including
stalling boot because `systemd-udev-trigger.service` fails to run after
switch-root, leaving udev with incomplete state.

verity-generator: disable default dependencies

---

dracut/30disk-uuid/90-disk-uuid.rules
dracut/30disk-uuid/disk-uuid.service
dracut/30disk-uuid/module-setup.sh

On first boot, the GPT table GUID will be set to
00000000-0000-0000-0000-000000000001. This service will generate a
proper GUID if the table GUID is still the default and after Ignition
has run. It is run after Ignition so that in the event that Ignition
fails to run, it won't successfully boot after a reboot.

table-guid: add service for generating GPT GUID

---

dracut/30ignition/module-setup.sh

--omit-network has been removed so that kernel options like
"ip=eth0:dhcp" are processed in the initrd. Networking may be needed for
Ignition to fetch the user_data.

dracut: add Ignition

---

dracut/30disk-uuid/disk-uuid.service

disk-uuid.service was racing with disk fscks and causing boot failures.
This was due to the GPT change triggering a udev partition re-scan
(which removes device symlinks) while the fsck was in progress.

dracut: add ordering on disk-uuid.service

---

dracut/02systemd-networkd/99-default.link
dracut/02systemd-networkd/module-setup.sh

The 80disable-net-names module installs 98-disable-net-names.link which
takes precedence over and conflicts with 99-default.link.
Just drop 99-default.link from the 02systemd-networkd module.

dracut: discard 99-default.link from 02systemd-networkd module

---

dracut/02systemd-networkd/initrd-systemd-networkd.service

The interfaces need to be reset to a pre-boot state so that userspace
after the switchroot can properly configure the interfaces.

dracut: take down all interfaces before switchroot

---

dracut/30disk-uuid/disk-uuid.service

To prevent disk-manipulating services ordered against disk-uuid.service
from racing with udev manipulating the associated device symlinks, settle
immediately after we write the GUID.

dracut: udevadm settle after writing the disk GUID

---

dracut/30ignition/module-setup.sh

Ignition needs these for manipulating the passwd/group dbs.

dracut: add useradd, usermod, groupadd to ignition module.

---

dracut/02systemd-networkd/initrd-systemd-resolved.service

This was causing a dependency cycle when coreos.ignition.force was
specified.

dracut: set DefaultDependencies=no for initrd-systemd-resolved

---

dracut/80setup-root/pre-pivot-setup-root.sh

The selinux symlinks need to exist before systemd is re-execed in order
to ensure that systemd can find and load the selinux policy.

Set up selinux tmpfiles before switching to root pivot

---

dracut/30disk-uuid/disk-uuid.service

The 766 branch is now excluding ignition but we still need disk-uuid so pull in its fixes.

Backport disk-uuid fixes to a pre-ignition revision

---

dracut/02systemd-networkd/zz-default.network

This snuck in from experimentation and should never have been merged.
It's being ignored by systemd-networkd, since .network files not
actually systemd units.

dracut: remove junk from zz-default.network

---

dracut/02systemd-networkd/zz-default.network

This is screwing with EC2's networking.

dracut: remove link-local addr from network config

---

dracut/99setup-root/initrd-setup-root

As of systemd v225 mount no longer is invoked with -n making the /etc/mtab
symlink necessary from an early stage.
Fixes https://github.com/coreos/bugs/issues/463

dracut: apply etc.conf in initrd-setup-root

---

update-bootengine

ldconfig does not work on non-native arches. Use the ldconfig
present in the target chroot to properly create the library cache.

update-bootengine: use the native ldconfig

---

dracut/99setup-root/initrd-setup-root

Our arm64 builds do not include SELinux and if this tmpfiles job fails
ignition fails causing the first boot to drop into an emergency shell.

initrd-setup-root: check selinux tmpfiles configs before using them

---

dracut/99setup-root/initrd-setup-root

Fix https://github.com/coreos/bugs/issues/447 yet again :(

setup-root: fix ordering between selinux-base.conf and libsemanage.conf

---

dracut/30disk-uuid/90-disk-uuid.rules
dracut/30disk-uuid/disk-uuid.service
dracut/30ignition/ignition-generator

Having udev add the disk-uuid.service want on-the-fly is racy.  Its
ordering will be ignored until wanted, so things like systemd-fsck-root
may get started before and run simultaneous to disk-uuid.service causing
random acts of badness.

dracut: use ignition-generator to require disk-uuid.service

---

dracut/30disk-uuid/disk-uuid@.service

Without this, systemd-fsck-root.service and disk-uuid.service get
started simultaneously when the root disk gets plugged.  Then
systemd-fsck-root.service fires *again* after sgdisk closes the device.
With this, disk-uuid.service runs to completion when the root disk is
plugged, before systemd-fsck-root.service, which not only prevents
potential overlap of execution but also eliminates the double fsck.

dracut: explicitly order disk-uuid before systemd-fsck-root

---

dracut/99setup-root/initrd-setup-root

It it possible for Ignition to manipulate users and groups via coreutils.
groupadd, for example, requires /etc/login.defs which is provided by
shadow.conf. shadow.conf requires /var/log which is created by var.conf. Include
both of these configs so that coreutils and Ignition can run.
Fixes https://github.com/coreos/bugs/issues/994.

dracut: run tmpfilesd with var and shadow configs

---

dracut/99journald-conf/00-forward-to-console.conf
dracut/99journald-conf/module-setup.sh

Following up from https://github.com/coreos/coreos-overlay/pull/1823.

dracut: add forward-to-console option to journald

---

dracut/99setup-root/initrd-setup-root
dracut/99setup-root/initrd-setup-root.service

First off, the script had a little bit of forgotten logic is left over
the read-only root and kexec days when things were much weirder and
allowing the setup to noop if /sysroot/usr wasn't mounted. This was
harmless until systemd 229 which includes the following change:
https://github.com/systemd/systemd/commit/104bc12fbc23c3ca852d9d389805c615cd590d01
So the fix is two fold: remove that bogus bit of logic so the setup
script explodes appropriately when /sysroot or /sysroot/usr isn't
mounted. Additionally fix the actual bug by ordering after
initrd-fs.target in addition to initrd-root-fs.target

setup-root: fix ordering with /sysroot/usr mount

---

update-bootengine

Replaces https://github.com/coreos/bootengine/pull/88
Conditionally removing the --no-kernel option makes for a more graceful transition.

update-bootengine: add support for bundling kernel modules

---

dracut/02systemd-networkd/module-setup.sh
dracut/90kernel-network-modules/module-setup.sh

Required for https://github.com/coreos/coreos-overlay/pull/2005
This is in lieu of updating dracut which is going to take a bit more work to test/fix/etc and I don't want to stall the kernel change on sorting out dracut.

dracut: install kernel network modules

---

dracut/02systemd-networkd/module-setup.sh
dracut/02systemd-networkd/yy-pxe.network

For coreos/bugs#1432, set the DHCP client identifier to the MAC address when using the PXE OEM.

dracut: set ClientIdentifier=mac for the PXE OEM

---

dracut/02systemd-networkd/yy-pxe.network

Using the MAC as the client identifier is needed when the machine-id is
transient. This almost always happens when the root filesystem is not
disk-backed (PXE booting). It's more accurate to check that the 'root'
kernel parameter is not specified, in which case a tmpfs will be
created.

dracut: change pxe network config condition

---

dracut/30ignition/module-setup.sh

This is needed to properly detect optical media and create the
/dev/disk/by-label symlinks for Ignition's OpenStack provider.

dracut: include cdrom_id rules

---

dracut/03coreos-network/module-setup.sh
dracut/03coreos-network/parse-ip-for-networkd.sh

I based the new hook on the upstream one for network configuration with normal tools.  This version really just added some bits for converting a netmask to CIDR notation (for networkd `Address` syntax), and it removed a lot of extra parts that are only relevant to the upstream module.

dracut: support initramfs network configuration via cmdline

---

dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

When run within QEMU, Ignition will now use the QEMU provider. Note that
this will not modify the kernel command line parameters, so later tools
will have to do their own detection.

dracut: add qemu detection to ignition generator

---

dracut/10diskless-generator/diskless-generator

`rootflags` is typically set to `rw`, which was causing the mode option to disappear.  Later mode options override earlier ones, so it's still possible to set the mode from the kernel command line.
Reported in https://github.com/coreos/bugs/issues/1812.

diskless-generator: Fix root directory mode 1777 on tmpfs

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition.target
dracut/30ignition/module-setup.sh

The Ignition units are intertwined with several other initramfs units maintained in bootengine, and are only useful when copied into the initramfs by the `30ignition` module.  Move them here for simplicity.
Unit files copied verbatim from coreos/coreos-overlay@fb0ebf975e572bae3486a515ac2887d39cd0a4f4.

dracut: Migrate Ignition unit files from coreos-overlay

---

dracut/30ignition/ignition-generator

Since systemd 233, a QEMU system using KVM has virtualization type "kvm", as opposed to the previous "qemu".  (It was back to "kvm" at some point several releases earlier.)  This sets the QEMU OEM ID value for both now, so Ignition is run on QEMU regardless of the systemd version or KVM support.

dracut: teach ignition-generator about kvm

---

dracut/30disk-uuid/disk-uuid@.service
dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-quench.service
dracut/30ignition/module-setup.sh
dracut/30ignition/sysroot-boot.mount

GRUB [now detects the first boot using a flag file in the EFI partition](https://github.com/coreos/scripts/pull/651) and passes `coreos.first_boot=detected` if found. In this case, enable an extra unit to delete the flag file after Ignition runs successfully. This ensures that Ignition will run on every boot until it succeeds, without having to change the disk GUID late in the boot process.  Randomize the disk GUID when GRUB asks us to do so, but go back to doing it independently of any Ignition run.
If there is no flag file, or the ESP cannot be mounted, `coreos.first_boot=detected` will intentionally cause a boot failure. Ignition can still be manually invoked by passing `coreos.first_boot=1` and we will not try to delete the flag file in that case.

dracut: Delete /boot/coreos/first_boot after automatic Ignition run

---

dracut/99emergency-timeout/module-setup.sh
dracut/99emergency-timeout/timeout.sh

Add a hook to emergency shell launch which prompts the user to press Enter, and then reboots if there's no response within 5 minutes. This should prevent systems from being stuck forever at a prompt if there's a boot failure in the initramfs.

dracut: Confirm entering emergency shell, reboot otherwise

---

dracut/99emergency-timeout/timeout.sh

Require the user to press Enter only once, and give them time to do it.

dracut: Fix emergency shell timeout with dracut breakpoints

---

dracut/20sysusers/ignition-sysusers.service
dracut/20sysusers/module-setup.sh
dracut/30ignition/ignition-files.service
dracut/99shadow/module-setup.sh

This commit does two things:
- Modify `dracut/99shadow/module-setup.sh` to run `systemd-sysusers`
during the dracut build to add user/group definitions to the
initramfs.
- Adds `systemd-sysusers` to the initramfs, and runs it before the
`ignition-files.service` unit. This is so that ignition can reference
and modify created users and groups.
Dependent on https://github.com/coreos/baselayout/pull/64

add sysusers to the initramfs

---

dracut/30ignition/ignition-generator

If ignition fails when running on EC2, systemd-networkd should be stopped so that the instance's status checks fail and indicate ignition's failure.
Fixes coreos/bugs#1890.

dracut: on ec2, disable systemd-networkd if ignition fails

---

dracut/30ignition/coreos-static-network.service
dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

Name the service `coreos-static-network.service` because there's nothing Packet-specific about its definition.  Probably `coreos-digitalocean-network.service` should be renamed to `coreos-dynamic-network.service` but that might break someone's journal monitoring.
Depends on https://github.com/coreos/coreos-metadata/pull/51.

dracut: Use coreos-metadata to configure Packet networking on first boot

---

dracut/30ignition/coreos-static-network.service

Ensure ignition-files can overwrite `/etc/hostname` (and potentially the networkd units). Fixes `coreos.ignition.*.sethostname` and `systemd.journal.remote` kola tests.
We do not do the same for coreos-digitalocean-network because that runs on every boot, so it'll have the last word anyway.

dracut: Run coreos-static-network before ignition-files

---

dracut/10verity-generator/module-setup.sh
dracut/10verity-generator/no-job-timeout.conf

`dev-mapper-usr.device` has a 90-second job timeout by default and is indirectly ordered after `ignition-disks.service` via `verity-setup.service`. As a result, long-running ignition-disks jobs would cause boot failures. Use an infinite timeout instead.
Addresses https://github.com/coreos/bugs/issues/2026.

dracut: prevent dev-mapper-usr.device from timing out

---

dracut/10verity-generator/verity-generator

863b403ff8537ccb8f21fd481892512f7c7f5452 removes the job timeout from `dev-mapper-usr.device`, but that timeout was the only thing causing us to drop to an emergency shell (and eventually reboot) if the verity root hash doesn't match the `/usr` partition. veritysetup detects this case and reports it to stderr but exits zero anyway; `dev-mapper-usr.device` then fails to finish starting for reasons that are not clear to me (the device node exists, can be opened, and reads properly return I/O errors). Fix by explicitly checking the verity status in the dm table. This should be race-free: we don't refer to the dm device by its device node, and we're performing the same status check that veritysetup performs at the end of its execution.

dracut: fail verity-setup.service if verity setup fails

---

update-bootengine

It prevents systemctl status and journalctl from complaining when run from the emergency shell:
WARNING: terminal is not fully functional
-  (press RETURN)
The cost is 6 KiB of image size.

update-bootengine: enable terminfo module

---

dracut/99raid-root-rules/65-md-raid-assemble-root.rules
dracut/99raid-root-rules/module-setup.sh

Add a udev rule to auto-assemble raid devices belonging to an array
ending in ROOT. This allows the root filesystem to be found when it's on
a raid array.

dracut: add module to assemble root raid array

---

dracut/03coreos-network/10-down.conf
dracut/03coreos-network/module-setup.sh
dracut/03coreos-network/network-cleanup.service
dracut/03coreos-network/yy-oracle-oci-bm.network
dracut/03coreos-network/yy-oracle-oci.network
dracut/90iscsi-root/iscsi-root-generator
dracut/90iscsi-root/module-setup.sh
dracut/90iscsi-root/oracle-oci-root.service

The upstream Dracut `iscsi` module is much more than we need, and would require several workarounds for CL. For now, support only Oracle OCI in a hardcoded way.
For https://github.com/coreos/bugs/issues/2036.

dracut: add module to start iSCSI root disk

---

dracut/03coreos-network/module-setup.sh
dracut/03coreos-network/yy-azure-sriov.network

The kernel will automatically bond it to the synthetic interface, so ensure networkd doesn't try to configure it separately.
initramfs equivalent of https://github.com/coreos/init/pull/259.

dracut: ignore Azure SR-IOV VF interface

---

dracut/99start-root/65-start-root.rules

Currently testing, don't merge just yet
The current invocation is broken (should be $env{DEVLINKS}) and
pointless, so drop it. The last arguments to the `mdadm --incremental`
command are just aliases that can be used in /etc/mdadm.conf (see the
"INCREMENTAL MODE" section of man 8 mdadm). We don't use
/etc/mdadm.conf in the initramfs, so just drop it.
cc @lucab since he was curious about this

99start-root: drop DEVLINKS from mdadm invocation

---

dracut/03coreos-network/yy-oracle-oci.network

Fixed upstream in systemd/systemd@e1c42e1b4097d575d8ac2222b2cc656fa256166b.

dracut: drop obsolete comment

---

dracut/99emergency-timeout/module-setup.sh
dracut/99emergency-timeout/timeout.sh

When timeout.sh is run due to a failed boot, check if either the ignition-disks or ignition-files units have failed. If they have, wait until journalctl has stopped receiving messages and then reprint the failed logs. Also print the emergency shell prompt via `\r` instead of `\n` so it doesn't slowly push the Ignition logs off the screen.
Waiting until journalctl has stopped receiving messages for 5 seconds (with a 15 second timeout) is a workaround for not being able to prevent systemd from printing to the console once the failure state is reached.
The motivation for this is to make it more obvious to users what went wrong when a machine fails to boot due to a bad Ignition config.
What this looks like in practice:
In QEMU:
In EC2:

dracut/99emergency-timeout: print explainer when Ignition fails

---

dracut/35torcx/module-setup.sh
dracut/35torcx/torcx-profile-populate-generator
dracut/35torcx/torcx-profile-populate.service

This adds a new `35torcx` module to bootengine, which takes care of
bringing `torcx-profile-populate.service` into initramfs.

dracut: add torcx-profile-populate service

---

dracut/35torcx/torcx-profile-populate.service

The BindReadOnlyPaths directive will create an empty file for the mount point if it does not exist, and it remains in place after the service stops.  In this case, an empty /etc/resolv.conf causes tmpfiles to skip creating the symlink to resolved's configuration, which results in no DNS resolution on the system.
As a workaround, call mount commands directly and remove an empty /etc/resolv.conf, which can't be blindly removed since users could have created a static configuration with Ignition.  Also, there is no touch command in the initramfs, so have bash open the file in append mode to ensure a mount point exists.

dracut/35torcx: Reimplement BindReadOnlyPaths to drop mount points

---

dracut/35torcx/torcx-profile-populate.service

This removes the dependency on `sysroot-boot` from
`torcx-profile-populate`, as the linked EFI-SYSTEM device is not
available on diskless PXE nodes.
The dependency itself is a leftover from a previous `ConditionPathExists`
for `first_boot` gating, which instead is now handled by `torcx-profile-populate-generator`.
Thus it should be safe to simply drop.
Ref: https://github.com/coreos/bugs/issues/2491

35torcx: remove unused dependency on sysroot-boot

---

dracut/30ignition/module-setup.sh

Fixes: https://github.com/coreos/bugs/issues/2481
This change allows to use proper Azure disk paths in ignition.

Add udev rules for Azure disks
